### ISSUE TITLE
JanICE.pdf can't be opened in Acrobat Reader

### ISSUE THREAD

**Issue by taa01776** [Noblis/janice#13]
Although it displays fine in my browser, the downloaded version of JanICE.pdf won't open in the latest Acrobat Reader (DC, version 2018.009.20050, Windows 10):
There was an error processing a page. There was a problem reading this document (15).

**Comment by JordanCheney** [comment]
Thanks @taa01776 I auto-generated the PDF using a Sphinx tool. I'm able to open the PDF in Preview on my Mac, I'll try with Adobe Reader and see if I can reproduce.

**Comment by taa01776** [comment]
Yes, it’s readable (and even printable) from inside my browser, so I’m not completely dead in the water, but… Sounds like it’s probably a problem with the Sphinx tool.

**Comment by JordanCheney** [comment]
@taa01776 Can you try and open the PDF I just pushed? I was able to open it in Adobe Reader

**Comment by taa01776** [comment]
That opens in Acrobat Reader (at least on Windows). Thanks!
