### ISSUE TITLE
Documentation of JaniceDetectionType is incorrect

### ISSUE THREAD

**Issue by taa01776** [Noblis/janice#14]
The documentation states that a JaniceDetectionType is an opaque pointer to a struct. In fact, a JaniceDetectionType *is* a struct (in janice.h, we have
typedef struct JaniceDetectionType* JaniceDetection;
), and a JaniceDetection is a pointer to it.

**Comment by JordanCheney** [comment]
@taa01776 Thanks for pointing this out. I am updating the documentation and will tag a patch release shortly.

**Comment by taa01776** [comment]
Thanks. Unfortunately, the way I came onto the program meant that I didn’t have time to review the API doc when it would’ve been appropriate, so I’m only running into things now as I work with them.

I can imagine uses for get(), but it should be something that can work on a const JaniceMediaIterator—one has an expectation for things called “get” that it doesn’t meet.

My current test for video-ness is, seek to 0 and call next() twice. If the second call fails, then it’s not a video. Not super-efficient. I’m planning to have my own IO library based on the reference implementation (it’s useful to point it at a directory and have it treat that collection of images as a video, for example), but my understanding is that we should be neutral with respect to the IO library, so the API will stay the same.
              -ta

**Comment by JordanCheney** [comment]
No problem, we will continue to update the API as comments come in. I should have mentioned up front however that any breaking changes will be kept on branch until we do the next release. Based on current schedules, that will be around the first week of March.

**Comment by taa01776** [comment]
While we’re on the subject—would it be unreasonable to add a janice_init_context call? The current janice_create_context API takes a JaniceContextType **, which presumably means that it allocates a new block of memory and populates it.
There are cases where a context is only needed temporarily; in C++, I’d just stack-allocate the thing and let it get cleaned up on function exit, but that’s not an option in C-land. However, if I had a call that took all of the same parameters as create_context, except with a JaniceContextType *, and just  filled in the structure pointed to, I could stack-allocate and not worry about any future changes in the structure.

In general, by the way, I would appreciate a better convention on naming things in the API. Probably it’s too late. But:
JaniceContextType, JaniceDetectionType, JaniceTemplateType, and JaniceGalleryType are all structs, with typedefs of JaniceContext, JaniceDetection, etc. as pointers to the structs.
All the other structs (JaniceRect,…) are just structs.
Because of the typedefs, this makes the documentation somewhat confusing—it is not immediately clear that an API that takes JaniceContext * is really struct JaniceContextType **, where JaniceRect * is struct JaniceRect *. It would be less so, I guess, if this special treatment were limited to implementation-defined types (JaniceDetection, …Template, and …Gallery), but then we get JaniceContextType thrown in there when it’s defined in the API includes. Yuck.
For that matter, the definitions of the implementation-defined types are unnecessarily restrictive. I think we really should be treating JaniceDetection, JaniceTemplate, and JaniceGallery as void * rather than struct XXXType: this restricts the implementation to passing around a pointer to a struct as the handle on those objects, and that’s not necessarily what it wants. (For example, in an application with lots and lots of templates flying around, it might be convenient to maintain an in-core cache, with JaniceTemplate just a cookie that’s used to query the cache. That’s pretty much precluded by this set of declarations.)
                -ta

**Comment by JordanCheney** [comment]
I'm fine with depreciating `janice_create_context` in favor of `janice_init_default_context(JaniceContext* context)` where the implementation can set reasonable defaults on a stack allocated context object i.e.

    // In user code
    JaniceContext context;
    janice_init_default_context(&context);

The plan for JaniceContextType was originally to be extended to hold implementation defined state, probably through an additional `void*` member. No one has stated that that is important to them in the current API, and I think most implementations use global state for sharing information anyways. This change would also make the naming convention more consistent as you suggest.

On your last point, could you define

    struct JaniceXXXType
    {
        void* data;
    };

To solve the use case you outline?

**Comment by taa01776** [comment]
The struct JaniceXXXType with a void * element is not the same as just having JaniceXXX be a void * (which I can cast to struct JaniceXXXType * if that's what I'm doing--albeit with a little bit less safety in the declarations).

**Comment by JordanCheney** [comment]
The version I proposed does require an extra dereference. If that cost is unacceptable you could always do the following (pseudo code)-

    struct JaniceTemplateType {};

    JaniceError janice_xxx(..., JaniceTemplate* tmpl)
    {
        int* s = (int*) malloc(sizeof(int));
        *tmpl = (JaniceTemplate) s;
    }

    JaniceError janice_xxx(JaniceTemplate tmpl, ...)
    {
        int* s = (int*) tmpl;
    }

The API has used this PIMPL idiom since the first release of Janus. Generally, I don't have a strong opinion on PIMPL vs `void*` but I would prefer not to make such a large change if there is an alternative.
