### ISSUE TITLE
JaniceMediaIteratorType documentation doesn't match reference implementation

### ISSUE THREAD

**Issue by taa01776** [Noblis/janice#15]
(Taking the reference implementation as the code in implementations/opencv_io.)
get() "advances the iterator to a specific frame and stores that frame..." However, the implementation sets the iterator, then calls next(), which will leave the iterator pointing *after* the specified frame. That should be clarified. (Generally speaking, a get() operator shouldn't have side-effects, but that's a different matter.)

seek() to 0 on an image (vs. video) iterator does not fail, and therefore neither will get(0), though the documentation calls for both to return JANICE_NOT_IMPLEMENTED on *any* image iterator.

On another note, as a client of the JaniceMediaIterator type, how would I know that it's a video rather than an image? Other than by seeing if a second call to next() fails, that is.

**Comment by JordanCheney** [comment]
@taa01776 Thanks for pointing this out. We are planning on depreciating the `get()` method in the next release of the API. As you point out it is poorly named and its implementation is equivalent to a `seek()` + `next()`. 

Based on this issue and on #16 we are going to modify the I/O API to make things easier. I will flesh this out in #16.

**Comment by JordanCheney** [comment]
Sorry, one last thing - `seek()` and `tell()` should return `JANICE_INVALID_MEDIA` if the media is an image. The documentation and reference implementation will be updated to reflect this.

**Comment by JordanCheney** [comment]
I'm closing this since the solution for this and #16 are the same. Please track progress on #16.
