### ISSUE TITLE
Is JaniceMediaIterators intentionally being passed by value?

### ISSUE THREAD

**Issue by taa01776** [Noblis/janice#18]
All of the APIs that take a JaniceMediaIterators parameter (janice>cluster_media, janice_detect_batch, janice_fine_tune, janice_enroll_from_media_batch) have
JaniceMediaIterators media
in their argument list. Which seems like it should be a pointer, but it's not--the parameter is being passed as a struct. Is this right?

**Comment by JordanCheney** [comment]
It can be passed as a const pointer (it shouldn't be modified in any of the functions) instead of being passed by value. This form is consistent with how the API passes all of the fully defined stucts (JaniceRect, JaniceTrack etc.).

**Comment by JordanCheney** [comment]
Discussion on this has moved to #26
