### ISSUE TITLE
Test harness template creation limited to stills only

### ISSUE THREAD

**Issue by taa01776** [Noblis/janice#19]
Which is OK for CS5, but not for IJB-C.
In particular, the code in  janice_enroll_detections.cpp calls janice_create_detection_from_rect on each line of the input file, rather than giving our code the chance to create a track from multiple entries with the same SIGHTING_ID.
Obviously we can all build our own harnesses, or just abandon IJB-C, but it seems like this would be a case worth handling.

**Comment by JordanCheney** [comment]
@taa01776 Agreed, I will update the harness

**Comment by JordanCheney** [comment]
@carlosdcastillo fleshed this out further in #25, I'm going to close this in favor of that issue. Please track the changes there
