### ISSUE TITLE
JanICE harness headers are inconsistent with protocol files

### ISSUE THREAD

**Issue by taa01776** [Noblis/janice#20]
I've been fixing this in our fork, so you'll get at least some cases corrected if you pull from there.
Even the CS5 protocol files have headers that are all upper case, with _ rather than camel case (TEMPLATE_ID, not templateId); many of the harness functions assume camel case, and therefore can't read the protocol files.

**Comment by JordanCheney** [comment]
@taa01776 Agreed, I will update the harness to be compatible with IJB-C
