### ISSUE TITLE
Test harness implementations interact badly with CS5 protocol outputs

### ISSUE THREAD

**Issue by taa01776** [Noblis/janice#22]
Obviously we'd prefer to use the test harness executables to generate output for future datacalls. However, some aspects of the implementation make that virtually impossible. The use of batch operations removes any path for returning actual detection times on individual images / frame sets back to a point where they can be included in the output file.
We will work around this by making private versions of the executables that support the information flow we need, but that seems quite wasteful...

**Comment by JordanCheney** [comment]
@taa01776 would you prefer a second set of executables that don't use the batch functions? The batch calls should allow higher throughput.

**Comment by taa01776** [comment]
Not sweating it. I’ve made my own harnesses for some of these anyway.
                                -ta

**Comment by JordanCheney** [comment]
Ok I'm going to close this for now then.
