### ISSUE TITLE
Test harness punctuation

### ISSUE THREAD

**Issue by taa01776** [Noblis/janice#23]
Invocations of macros like JANICE_ASSERT in the test harness should always be followed by a semicolon:
JANICE_ASSERT(...);
*not*
JANICE_ASSERT(...)
The extra semicolon doesn't hurt the C compiler, and helps editors (like Emacs) deal with the syntax better.

**Comment by JordanCheney** [comment]
I'll accept a PR on this, I don't care either way.

**Comment by JordanCheney** [comment]
Closing this, it's fixed on master (thanks!) and in v6
