### ISSUE TITLE
Need to get SIGHTING_ID from media

### ISSUE THREAD

**Issue by carlosdcastillo** [Noblis/janice#25]
UMD needs this. Probably we also want the file name attached to media.

This is something that has been discussed a couple of times in the past. See for example: https://github.com/Noblis/janus/pull/41#issuecomment-255167766

With each change to the API it gets clobbered and we need to start from scratch. I have an implementation let me know if you want it as a pull request. It only changes janice_io adding one function pointer, well two, one to pull in the file name (see above).

**Comment by JordanCheney** [comment]
@carlosdcastillo Sorry about losing this. Just to rehash the original issue in terms of JanICE to make sure we're on the same page- In the mixed protocol, you can be passed multiple `JaniceMediaIterators` to enrollment which are actually key frames from the same video. This information is exposed in the IJB-C CSV as SIGHTING_ID which you want to use to do a merge of related media before processing. Currently, that information is not exposed by the API so you can't do this.

In Janus, we solved this by creating a single sparse iterator for key frames and I would like to do the same here if you're amenable. This is a niche application for this program so I would prefer not to modify the I/O API. Instead, I will add a new function to the opencv_io implementation, `janice_io_opencv_create_sparse_iterator` or similar, which will create a single `JaniceMediaIterator`. You can use `next()` to move between key frames and `tell()` to get the appropriate frame numbers. Does that work?

**Comment by carlosdcastillo** [comment]
Yeah, sounds good. So long the user can send in something from which I can derive where each frame comes from and which have common sources we can use this at template construction time, it is not niche. Building templates is central to the program 

Remember the following pain points from the past:

1. I would like to know which media iterators are sparse and which are dense (the code paths are different for each). A template is either one dense iterator (I believe the program is not not focusing on this case as much as the cs3-cs4 time), or one or more sparse iterators (not both).
2. For sparse, Frame index should be based on the iterator and not on the video they come from
3. For dense, the frame index should be based on the video they come from
4. In the past we had FPS for dense and no FPS for sparse, that may be useful and I don’t see it anymore.
5. A single image can be a sparse media iterator of length one.

Thanks!

**Comment by JordanCheney** [comment]
In combination with #16  I'm proposing updating the interface as follows:

* Dense video iterator
    * `is_video` -> sets bool to true returns `JANICE_SUCCESS`
    * `get_frame_rate` -> sets float to frame rate returns `JANICE_SUCCESS`
* Sparse video iterator
    * `is_video` -> sets bool to true returns `JANICE_SUCCESS`
    * `get_frame_rate` -> returns `JANICE_INVALID_MEDIA`
* Image
    * `is_video` -> sets bool to false return `JANICE_SUCCESS`
    * `get_frame_rate` -> return `JANICE_INVALID_MEDIA`

**Comment by JordanCheney** [comment]
@carlosdcastillo Can you review the new 6.0 branch to see if the interface and harness executables match what you expected?

**Comment by carlosdcastillo** [comment]
I think there are a couple of problems. media->get now on purpose is not working on images. How do I iterate through a media that has multiple images? 

Also, the create gallery harness program is broken.

**Comment by carlosdcastillo** [comment]
When I say images I mean an image. It used to be possible to do media->get(media, &img, 0); on a media that represented a single image. Now: https://github.com/Noblis/janice/blob/6.0/implementations/opencv_io/janice_io_opencv.cpp#L184-L186

There seems to be good reason to disallow it. Not sure what happened.

**Comment by JordanCheney** [comment]
You can get an image by calling `media->next(media, &img)`. I changed the function to match the documentation, which states that `seek`, `get` and `tell` should only work on videos. I will add `get` and `seek` to sparse media iterators.

**Comment by carlosdcastillo** [comment]
Let me see if I get this right:

- get is for videos, yet for the version in master worked for images, v6 now fails on videos, as spec requires
- next is for images, except that unlike get it is stateful (i.e. it reaches the end) where get does not. it returns JANICE_MEDIA_AT_END when this happens
- except that there is currently no get for sparse, but sparse is a video, at least when you ask is_video

For example when enrolling from detections, first we get detections from rect or track(which means look at the images), I have to do next.

Then enroll from detections has to look at the image again. At this point every media is at end. When sent in nothing should be at end.

janice_io should be a library to unify access to heterogenous media sources. Let's not get bogged down in the code and pointers and specs. Right now janice_io is delegating everything to the implementer (and itself is not necessarily a problem) but in doing so it behaves weirdly and arbitrarily.

**Comment by JordanCheney** [comment]
536937e implements `get()` and `seek()` for sparse iterators so it conforms to the video interface. I removed the ability to provide explicit frame numbers per the conversation in #26. I will update the documentation for functions that take `JaniceMediaIterators` as inputs. The iterators will be left in an an unknown state (for example AT_END) after the function call. Users need to call `reset()` if they would like to use the iterator again.

**Comment by JordanCheney** [comment]
c277a87 updates the documentation to require uses to reset iterators after they are used. a0cb9aa implements that in `janice_enroll_detections.cpp`.
