### ISSUE TITLE
V6 create gallery broken

### ISSUE THREAD

**Issue by carlosdcastillo** [Noblis/janice#28]
There's a bug here:
https://github.com/Noblis/janice/blob/6.0/harness/janice_create_gallery.cpp#L84-L100

cnt needs to be updated appropriately.

**Comment by carlosdcastillo** [comment]
Something like: pos = pos + args::get(batch_size); needs to be added at the end of the outer for loop to unbreak it.

**Comment by JordanCheney** [comment]
Thanks! Should be fixed in 86423c6
