### ISSUE TITLE
default of 0 returns is not useful for search

### ISSUE THREAD

**Issue by carlosdcastillo** [Noblis/janice#31]
Needs to default to 50. Search with zero max_returns is not interesting:
https://github.com/Noblis/janice/blob/6.0/harness/janice_search.cpp#L23

**Comment by JordanCheney** [comment]
0 indicates all possible matches should be returned. Documentation is [here](https://noblis.github.io/janice/api/comparison.html#janice-search)

**Comment by carlosdcastillo** [comment]
Oh... sorry, I will fix that in my implementation.

**Comment by carlosdcastillo** [comment]
Wait, @JordanCheney. @svebk who's working with us to include sub linear search into the deliverable would like to comment further.

**Comment by svebk** [comment]
@JordanCheney @carlosdcastillo This setting of max_returns to 0, with a default threshold of 0 and with all scores being positive, would make this function return all templates in the gallery, even if there are millions of templates in the gallery. Is this really the expected behavior? This also means the sub-linear is not of benefit in this situation?

**Comment by JordanCheney** [comment]
@svebk In most cases I would expect users to set either the `max_returns` or `threshold` (or both). I can change the default value if that is concerning you. However, users should have the ability to do an exhaustive search if they choose.

**Comment by svebk** [comment]
@JordanCheney I still see the interest in having the possibility to perform the exhaustive search, and we will handle this setting, but I share @carlosdcastillo concerns that a default value of 50 or 100 would be more reasonable. We believe a default setting should be reasonable without the user really knowing the details of the parameters, and the default setting of `0` for both `threshold` and `max_returns` isn't really.

**Comment by carlosdcastillo** [comment]
@JordanCheney I think the defaults should guide the users towards use cases where fast solutions exist. They should need to go out of their way to have to do full linear search.

**Comment by JordanCheney** [comment]
Done in d1bbdec
