### ISSUE TITLE
Image loading should ignore EXIF rotation flags

### ISSUE THREAD

**Issue by taa01776** [Noblis/janice#34]
initialize_media_iterator in janice_io_opencv.cpp calls cv::imread() with flags such that it honors rotation specified in the image's EXIF data (if there is any). However, the ground truth for CS5 applies to the unrotated image, and the caller has no way of knowing whether rotation happened.
Should perhaps add the IMREAD_IGNORE_ORIENTATION flag to the cv::imread() call?

**Comment by JordanCheney** [comment]
Neat flag, I hadn't seen it before. It looks like it was added in OpenCV 3.3? I'll update the implementation and the CMakeLists.txt to require 3.3 or higher. 

@carlosdcastillo FYI since this will change how the images are loaded. This should eliminate some out of bounds annotations.

**Comment by carlosdcastillo** [comment]
@JordanCheney I'm gonna be honest with you. I've had it with OpenCV 3.x. I'm using 2.4.13 and that is what I will ship with the deliverable and my janice_io will run OpenCV 2.4.13. I can go over a list of reasons why I won't be using 3.x.

I would assume that in 2018 it is possible to compile janice_io with OpenCV 3.3 and umd_janice with OpenCV 2.4.13 and they should all play well together and all. But I'm so sure that C++ hasn't gotten to that point that I'm not going to even waste my time trying that. 

The purpose of janice_io is to be switchable. So perhaps you can switch it. You guys are young, you can try. The UMD blessed implementation of janice_io will be compiled by me with 2.4.13.

**Comment by JordanCheney** [comment]
@carlosdcastillo I appreciate the honesty :) This shouldn't cause any issues. I'm guessing you already forked opencv_io or you wrote your own as it required 3.X before. 

@taa01776 This is implemented in 5907342.
