### ISSUE TITLE
janice_search harness output should match protocol

### ISSUE THREAD

**Issue by taa01776** [Noblis/janice#35]
The current (6.0) implementation produces PROBE_ID, GALLERY_ID, SCORE in the output.
For candidate files, we're expected to provide
SEARCH_TEMPLATE_ID, RANK, ERROR_CODE, GALLERY_TEMPLATE_ID, SCORE, SEARCH_TIME

**Comment by JordanCheney** [comment]
Fixed in c1fc062.
