### ISSUE TITLE
Various harness programs still pass JaniceContext by value

### ISSUE THREAD

**Issue by taa01776** [Noblis/janice#36]
janice_detect.cpp, in call to janice_detect_batch
janice_cluster_templates.cpp, in call to janice_cluster_templates
janice_enroll_detections, in call to janice_enroll_from_detections
janice_enroll_media, in call to janice_enroll_from_media_batch,
janice_search, in call to janice_searcH_batch

**Comment by JordanCheney** [comment]
Solved by your PR thanks!
