### ISSUE TITLE
Would be handy if seek to 0 on media iterators worked on images, as it did before v 6.0

### ISSUE THREAD

**Issue by taa01776** [Noblis/janice#38]
This was convenient in the previous version of the implementations directory.
Pull request will follow.

**Comment by JordanCheney** [comment]
@taa01776 I'm hesitant to change this back given that we just changed it and I imagine the other performers are writing to the current spec. Is not having this causing an issue with your code?

**Comment by taa01776** [comment]
Yes, it was, until I put in the changes that are in the PR. This would matter to others only if UMD were depending on a seek/get failure to indicate a video file, no?
                -ta

**Comment by JordanCheney** [comment]
If @carlosdcastillo can confirm this isn't an issue for him I will update the documentation and accept the PR.

**Comment by JordanCheney** [comment]
Merged
