### ISSUE TITLE
JanICE batch APIs could do with a little more metadata

### ISSUE THREAD

**Issue by taa01776** [Noblis/janice#42]
For example (an issue that's come up in testing), janice_enroll_from_detections_batch takes a media iterators group and a detections group, and populates a JaniceTemplates structure. This is quite reasonably called to create probe templates for the 1:N probe protocol, among other things.
Unfortunately, if there's a problem in the ...batch() call, there is no way for us to have reported the template ID (which comes from the protocol input file) that's being processed: no place for template IDs in either the detections group or the media iterators group, and the templates don't exist yet: they'll get IDs upon return from the call.
Would be handy if there were an additional parameter (which could be null, of course) that would let the template IDs be logged as they were being created, so on a crash we could easily identify the culprit.

**Comment by JordanCheney** [comment]
Hey @taa01776 sorry for the delay I was out of the office. I'll put together a PR for additional debugging information in the batch calls.

**Comment by JordanCheney** [comment]
I think this is resolved with the new batch error codes in #51
