### ISSUE TITLE
How best to support video clipping / downsampling?

### ISSUE THREAD

**Issue by taa01776** [Noblis/janice#43]
It would be extremely useful for testing (and we could make a pretty good case that it would be useful operationally as well) to provide support in the APIs for some additional parameters related to videos: start frame, end frame, and desired frame rate. Obviously we can do this by building our own MediaIterator implementation that takes a few additional arguments to the constructor. The disadvantage of that approach is that the MediaIterator API itself doesn't provide any way to extract those additional parameters later on, which makes it much harder to generate understandable outputs, error messages, and log files.

For example: a detection in a frame of a video that's been downsampled to 6 FPS should ideally have the same frame number that it would have if the video had not been downsampled--but there's no API-compliant way to get that information.

I'll be coding _something_ to address this, but it'd be good if I could do something with a high likelihood that my pull request would get merged. As I see it, the options are:
- Enhance the MediaIterator API to accept some additional parameters (for videos) at creation, and provide a new method on MediaIterator that can map a logical frame number back to the physical frame number within the video.
- Add new fields to JaniceContext that can be filled in by the caller, specifying start frame, end frame, and some variation on frame rate. This might require adding a context parameter to janice_create_detection_from_rect and _from_track, which are the only APIs currently that take a MediaIterator without a context.
- Handle as additional "--algorithm" pieces on the harness executable command lines, whereupon (in our implementation) the arguments become part of the parameter set. That fails if an executable is going to be used on more than one video, which is our most common use case.

Obviously my preference is to put the change into the MediaIterator, if that's something that's likely to get accepted into the API. Please advise.

**Comment by JordanCheney** [comment]
I think doing this in media iterator makes the most sense. 

For my understanding I think your changes to the MediaIterator API boil down to 
* the "logical" position is the number of times `next()` has been called while the "physical" position is the actual frame in the underlying video
* All of the media iterator video methods (`seek()`, `get()`, `tell()`) would continue to take or return the logical position in the iterator. 
* The change would be a new method that maps the logical frame to the physical one. 
* The physical frame is only useful for debugging and logging, it's not the expected input to any other methods. 

If that is all correct I'd have no issue accepting it into the API. I think in some contexts there won't be a mapping (for example sparse iterators) so it might make sense to add an error type- `JANICE_NO_FRAME_MAPPING` that could be returned so callers can fail gracefully.

**Comment by JordanCheney** [comment]
Merged #44
