### ISSUE TITLE
Provide callback to support faster reporting of detections

### ISSUE THREAD

**Issue by taa01776** [Noblis/janice#46]
I think in principle it is possible to run detection from a live video stream (as opposed to a .mp4 file)--at least, the OpenCV calls support that.
One thing that would make that much more useful is a mechanism to report detections as they are found, rather than waiting until janice_detect / janice_detect_batch returns--on a long video, or on a stream, that can be an arbitrarily large amount of time.
Something on the order of 
`JaniceError (*report_detection)(JaniceMediaIterator media,  // required if called from janice_detect_batch
                                                JaniceDetection detection);`
would probably be enough (could add a detection time parameter as well, though the user could get that into JaniceDetection). The semantics of a non-JANICE_SUCCESS return could go one of two ways: either it just gets logged as a failure, or a specific (potentially new) error return means, "don't return this from the call."
Of course, passing this could mean that the JaniceDetections / JaniceDetectionsGroup values won't be filled in at all--it's up to the callback to do something with the data coming back.

**Comment by JordanCheney** [comment]
Added in #51
