### ISSUE TITLE
Perhaps a couple more JaniceError codes would be helpful?

### ISSUE THREAD

**Issue by taa01776** [Noblis/janice#47]
There are cases in the API implementation where one of the internal functions wants to return a valid JaniceError code, which will probably end up in the hands of the original caller. It would be useful if there were an error code or two that didn't mean "unknown" without being completely specific to the JanICE API. Even something as basic as JANICE_IMPLEMENTATION_ERROR or JANICE_INTERNAL_ERROR would allow some distinction between "I have no idea what's going on" and "I just encountered an error that I don't expect, but at least was checking for..."

**Comment by JordanCheney** [comment]
@taa01776 I've added JANICE_INTERNAL_ERROR in #51. If you would like other codes feel free to open a PR and add them- more is better in my opinion.
