### ISSUE TITLE
Callback from enroll APIs would also be useful

### ISSUE THREAD

**Issue by taa01776** [Noblis/janice#48]
Similar to what I suggested in #46 for the detector, a callback option for the enrollment APIs could also be handy. It's not as valuable to building systems that operate on data streams, but would make templates available as soon as they're ready (e.g., for probes), vs. waiting for a whole batch to be processed.

janice_enroll_from_media... could conceivably use both callbacks, but that might be gilding the lily.

**Comment by JordanCheney** [comment]
Fixed in #51
