### ISSUE TITLE
JanICE harness implementation can't run IJB-C 1:1 mixed protocol

### ISSUE THREAD

**Issue by taa01776** [Noblis/janice#53]
This is still an issue in v7.
In the janice_verify main() function, there's a test: reference_tmpls.size() != verification_tmpls.size(); the process dies if that condition is true. This is a carry-over from the janus implementation, where it required the two lists of template IDs to be the same length--but those were vectors of template IDs, with much duplication, where reference_tmpls and verification_tmpls are maps.
The real requirement is that the left side and the right side of the comparison have the same number of elements, but that's different.

**Comment by JordanCheney** [comment]
@taa01776 this was fixed in 6e2e741
