### ISSUE TITLE
Query regarding commit 39687b1

### ISSUE THREAD

**Issue by taa01776** [Noblis/janice#54]
It seems like most of the JaniceMediaIterator functions now take a const JaniceMediaIterator *, which in my understanding means that the JaniceMediaIterator object referred to by the pointer is constant during the operation. This seems wrong: certainly next(), seek(), and reset() will change the structure; further, it makes it impossible to lazily initialize the media iterator. The is_video, get_frame_rate, and get_physical_frame_rate operations all require that the underlying media be open in order to succeed; this precludes an approach where the media iterator gets created, but isn't actually initialized until someone tries to access it.

**Comment by JordanCheney** [comment]
@taa01776 confusion on my end on the semantics of const type* and type* const- I'm going to revert. 

I made this change originally because janice_detect etc. take a `const JaniceMediaIterator*` but the iterator functions take a `JaniceMediaIterator*`. I will switch both to `JaniceMediaIterator*`

**Comment by JordanCheney** [comment]
This should be fixed by 73a6b1e
