### ISSUE TITLE
janice_initialize calls in janice/harness don't match janice/api/janice.h

### ISSUE THREAD

**Issue by taa01776** [Noblis/janice#56]
Possibly a missing commit? The calls to janice_initialize() in all of the harness executables take an additional ignored_errors parameter (from 7/17, commit 6e2e741d?), but janice_initialize() as declared in janice.h does not. The most recent change in janice.h appears to be from 7/9.

**Comment by JordanCheney** [comment]
The janice_initialize call takes the same parameters as before. `ignored_errors` is a parameter for JANICE_ASSERT so the harness doesn't automatically exit.
