### ISSUE TITLE
ISI Feedback

### ISSUE THREAD

**Issue by stephenrawls** [Noblis/janice#6]
Hi,

Here is ISI's feedback for the JanICE API.

1. The JanICE initialization function could be modified to provide a list of GPU's available as opposed to a single GPU. The underlying recognition engine could make use of this for better GPU utilization and faster processing times for machines with multiple GPU's.

2. The JanICE initialization function could also be modified to indicate how many threads and/or CPU cores the underlying engine is allowed to use. For example, a value of "-1" might indicate the underlying engine is allowed to use as many threads as possible, while a value of N (>0) indicates the the maximum number of allowable threads/CPU cores to use. This will make the code play nicely with systems where other code is expected to run on the same machine.

3. It might be useful to have a janice_create_gallery() function which takes a list of template files as input as opposed to a list of template objects in memory. The motivation of this would be so you don't have to load all templates into memory at once when calling janice_create_gallery(). Alternatively this could be achieved by the current API with multiple calls to janice_gallery_insert(), but if so, then it would be useful to have a way to let the gallery know the expected number of total templates in advance, e.g. something like janice_gallery_reserve(N), so that our code can allocate sufficient memory for N subjects without wasting a lot of time on re-allocating/copying memory with successive cals to janice_galery_insert().

Thanks,
Stephen Rawls (ISI)

**Comment by JordanCheney** [comment]
Hi Stephen, I forgot to close this but batch function were added in version 5.0. I think they address all of your feedback here.
