### ISSUE TITLE
Videntifier Feedback

### ISSUE THREAD

**Issue by thorsteinssonh** [Noblis/janice#9]
Hi, I'm opening this thread to cover feedback from Videntifier Technologies' side regarding integration of SPN fingerprinting and matching with JanICE.

My first impressions are that it is a great idea to try to abstract commonalities between facial recognition and camera hardware recognition software.  

1. in combining FR and (SPN - call it HR) into a common API, I agree there is a good overlap regarding i/o, media processing and the concept of 1:1 and 1:N matching and databases (galleries). However, there are likely also many key dissimilarities because one is concerned with the visual content of images while the other is concerned with the image file itself and how it was made.  I think this means we have to be very careful to keep the API intuitive to both FR and HR users, and at a level of the most lowest common denominator if possible.

2. I initially got confused by the nomenclature of the Janice API.  I think the concept of a 'template' for example got me stuck.  I realize now that these are terms traditional to biometrics :) and after a little wikipedia read on biometrics I feel like I understand better the concept of the API.  So, in my own language, please correct me :),  the API has a concept of,
  * raw data (media types), 
  * a statistical model, modeling the features that can be contained in the data (template)
  * extracted data (inferences) based on the chosen template ( extracted data sometimes referred to as fingerprints, but also sometimes as templates? )
  * clusters of fingerprints, which are also types of fingerprints / templates
  * database of fingerprints referred to as a gallery.

3. Do you intend Janice to function as a simultaneous integration into two separate types of algorithms, e.g. both SPN and FR at the same time the implementer switching between them?

I'll continue to make further comments here as I understand more about the API :)

**Comment by JordanCheney** [comment]
@thorsteinssonh I am going to close and move this thread to a new repository
